POST http://localhost:8080/events/1/register
# Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFydGVtIiwiZXhwIjoxNzU5NzU5MDgzLCJ1c2VySWQiOjJ9.nPaavkgJ4yYL7Oo7HiCSLv6ZboWfwClaxlFqj1zltfs
